### PR TITLE
Revise how Julia exceptions are handled

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Good point. No, it is not really. I'll clang-format this PR, too.

**Comment by fingolfin** [comment]
BTW, the names BEGIN_JULIA / END_JULIA are of course not great, feel free to rename them.

Next, one thing that I dislike about them is that one *must not use `return` or `ErrorQuit` inside such a block. That's easy to forget. I'll at least add a comment.

**Comment by sebasguts** [comment]
I think the names are okay for now, no need to change them. try/catch are not really fitting here, so okay.

Can we configure `clang-format` to do the indentation? I would really like it.

**Comment by fingolfin** [comment]
Hmm, looking at https://clang.llvm.org/docs/ClangFormatStyleOptions.html this can be done with `MacroBlockBegin` and `MacroBlockEnd`. However, this requires a recent version of `clang-format` I think (LLVM 4.x or newer). I've updated the PR now.

**Comment by sebasguts** [comment]
Nice one, thank you :)

**Pull request merged**
